export const ADD_FLASH_MSG = 'ADD_FLASH_MSG';
export const DELETE_FLASH_MSG = 'DELETE_FLASH_MSG';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';

export const SET_DATA_LIST = 'SET_DATA_LIST';
export const DELETE_DATA_LIST = 'DELETE_DATA_LIST';

export const SET_SENSORS_LIST = 'SET_SENSORS_LIST';
export const DELETE_SENSORS_LIST = 'DELETE_SENSORS_LIST';