export const ADD_FLASH_MSG = 'ADD_FLASH_MSG';
export const DELETE_FLASH_MSG = 'DELETE_FLASH_MSG';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const DELETE_CURRENT_USER = 'DELETE_CURRENT_USER';

export const SET_DATA_LIST = 'SET_DATA_LIST';
export const DELETE_DATA_LIST = 'DELETE_DATA_LIST';

export const SET_SENSORS_LIST = 'SET_SENSORS_LIST';
export const DELETE_SENSORS_LIST = 'DELETE_SENSORS_LIST';

export const SET_METEO_LIST = 'SET_METEO_LIST';
export const DELETE_METEO_LIST = 'DELETE_METEO_LIST';

export const SET_ACTIVE_SENSORS_LIST = 'SET_ACTIVE_SENSORS_LIST';
export const DELETE_ACTIVE_SENSORS_LIST = 'DELETE_ACTIVE_SENSORS_LIST';

export const SET_STATION_LIST = 'SET_STATION_LIST';
export const DELETE_STATION_LIST = 'DELETE_STATION_LIST';
export const FIRST_STATION_LIST = 'FIRST_STATION_LIST';

export const SET_MACS_LIST = 'SET_MACS_LIST';

